name: Публикация Docker-образа

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Сборка и отправка образа в GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v7
      
      - name: Авторизация в GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Сборка и публикация Docker-образа gmod-server
        uses: docker/build-push-action@v6
        with:
          context: ./gmod-server
          push: true
          tags: |
            ghcr.io/seray-orig/gmod-server:latest
            ghcr.io/seray-orig/gmod-server:${{ github.ref_name }}

      - name: Сборка и публикация Docker-образа steamcmd
        uses: docker/build-push-action@v6
        with:
          context: ./steamcmd
          push: true
          tags: |
            ghcr.io/seray-orig/steamcmd:latest
            ghcr.io/seray-orig/steamcmd:${{ github.ref_name }}